"""Add email column to job table

Revision ID: 4092a796db47
Revises: 759ec68950d7
Create Date: 2024-07-27 14:45:46.512035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4092a796db47'
down_revision = '759ec68950d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])

    with op.batch_alter_table('jobseeker', schema=None) as batch_op:
        batch_op.drop_index('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobseeker', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=True)

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
