"""Added resume to the db model

Revision ID: 7439011115b7
Revises: 1aa9f4f9be6f
Create Date: 2024-07-29 23:04:38.155448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7439011115b7'
down_revision = '1aa9f4f9be6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appliedjob', schema=None) as batch_op:
        batch_op.alter_column('resume',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appliedjob', schema=None) as batch_op:
        batch_op.alter_column('resume',
               existing_type=sa.String(length=150),
               type_=mysql.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
