"""Modified many schemas

Revision ID: 759ec68950d7
Revises: bfb8a8b0f79a
Create Date: 2024-07-25 12:49:33.199217

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '759ec68950d7'
down_revision = 'bfb8a8b0f79a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_website', sa.String(length=255), nullable=False))
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('company_logo',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('employer', schema=None) as batch_op:
        batch_op.alter_column('company_logo',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.drop_column('company_website')

    # ### end Alembic commands ###
